
FROM antmoveh/centos-lvm2:v4

# copy binary file
COPY bin/carina-node /usr/bin/
COPY bin/carina-controller /usr/bin/
COPY debug/config.json /etc/carina/

RUN chmod +x /usr/bin/carina-node && chmod +x /usr/bin/carina-controller

# Update time zone to Asia-Shanghai
COPY Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone

CMD ["echo carina-node carina-controller"]
