{{- if .Values.kubeconfig.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-kubeconfig
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
type: Opaque
data:
  config: '{{ .Values.kubeconfig.secret }}'
{{- end -}}
