apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: carina-stateful
  namespace: carina
  annotations:
     carina.storage.io/allow-pod-migration-if-node-notready : "true"
spec:
  serviceName: "mysql-service"
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        carina.storage.io/allow-pod-migration-if-node-notready : "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysqlpod
          image: mysql:5.7
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          ports:
            - containerPort: 80
              name: my-port
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: csi-carina-sc
        resources:
          requests:
            storage: 3Gi
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: carina
  labels:
    app: mysql
spec:
  ports:
    - port: 80
      name: my-port
  clusterIP: None
  selector:
    app: mysql